### ISSUE TITLE
Supporting Jobs triggered by plug-ins, API and scripts

### ISSUE THREAD

**Issue by bes3** [biouno/uno-choice-plugin#60]
In Uno-choice widgets seems that the Value Scripts is not evaluated when the Job is launched from events or automatically (without user interaction) and the parameter is null.

Here an example of this beahviour comparing Uno-choice widgets (version 0.21) against others common input control widget such as Dynamic Parameter and Dynamic Choice Parameter.

'''JOB CONFIGURATION AND BUILD VIEW'''
I removed some job and plugin configuration that I left empty.
![img1](https://cloud.githubusercontent.com/assets/9929049/5218317/a80fd82c-764b-11e4-9c84-1ab2c66cbfeb.jpg)

'''BUILD RESULT'''
I executed two kind of build:
- Build15 has been launched manually by me and as you can see all the parameters are corretly populated
- Build 16 has been launched automatically and Dynamic Parameter and Dynamic Choice Parameter have value but Dynamic Choice Parameter hasn't (it seems that Value Script is not evaluated)

![ticket2](https://cloud.githubusercontent.com/assets/9929049/5218320/b0dc7d84-764b-11e4-8a5d-0822551b82ed.jpg)

**Comment by jrampon** [comment]
Hello, I'm having the same issue. This is new behavior from version 0.21 though. The previous version I was using, 0.19, was correctly setting values when run from a timer. I had to revert to it until this issue gets fixed.

**Comment by kinow** [comment]
Hi @jrampon ! Thanks for your pointer. I thought that this had never worked before. And a special thanks for pointing the versions you were using. I'll check the changelogs to see if we can figure out what's happening.

**Comment by kinow** [comment]
Will try to include this in the next sprint, maybe we can ship this with 1.0.

**Comment by kinow** [comment]
Successfully reproduced it locally, used a vanilla parameter, a parameter provided by the dynamic parameter plugin, and another unochoice parameter. Investigating...

**Comment by kinow** [comment]
Bit of background to explain what went wrong, and why the dynamic-parameter-plugin worked...

In the past we worked only with lists, as the dynamic-parameter-plugin. However, after users requested to be able to define the key:value's of some HTML elements (like `<SELECT>` elements), we migrated the underlying data structure that holds parameter values in the UI to a `java.util.Map`.

This part of the code didn't change since the initial code:

```
firstElement = choices.get(0);
```

Interestingly, it works correctly for java.util.List, but returns null for java.util.Map for our parameters. I've used the correct way to retrieve the first element, though I didn't make much validations, since I'm assuming the element will be there and it will be non-null. 

Let me know if you spot any issue that could be related to this change. Thankfully I think we'll be able to ship this issue with 1.0 :-)

Thanks for reporting the issue and for the patience to all involved. 
Bruno

**Comment by varjojukka** [comment]
I tested this with version 0.23 (https://groups.google.com/forum/#!topic/biouno-developers/REx4-sk_xSs) and found one thing still not working: regardless of groovy script default selection (described in https://wiki.jenkins-ci.org/display/JENKINS/Uno+Choice+Plugin) or selected "choice type" the triggered build results in including only the first item in the return list. This applies to at least "single choise" and "check box" choice types. Especially with "check box" there can be more than one value selected and returning only the first list item is not very convenient.

Config:
![uno-choice-default_config_checkbox](https://cloud.githubusercontent.com/assets/7567993/6780922/fdb59f60-d171-11e4-85f4-2075efd61df4.png)

Build:
![uno-choice-default_build_checkbox](https://cloud.githubusercontent.com/assets/7567993/6780935/2191e164-d172-11e4-883d-250149202ca3.png)

Parameters:
![uno-choice-default_params_checkbox](https://cloud.githubusercontent.com/assets/7567993/6780923/fdb5c26a-d171-11e4-943f-a1d5da6cc825.png)

**Comment by kinow** [comment]
Hi @varjojukka, I am working to fix an issue with certificates in the update center, but will try to reproduce and investigate the issue in the next days. Feel free to update this issue should you have any new information. Thanks!

**Comment by imoutsatsos** [comment]
@varjojukka Try adding a 'dummy' referenced variable and see if this fixes it. I had some situations where I needed to pass in a referenced parameter to get this to work (with v0.23) . So add something like TEST for a referenced parameter. It does not have to exist in the Jenkins parameters.

**Comment by varjojukka** [comment]
Thank you for the tip but dummy reference parameter did not solve the issue in my case using Jenkins ver. 1.588 and 1.580.3. Also the text ":selected" is included in the parameter name if used on the first return list item.

**Comment by imoutsatsos** [comment]
@varjojukka I have been unable to reproduce the issue using Chrome with Jenkins-CI ver 1.598 and the latest Uno-Choice plugin. Both Dynamic Choice and Cascade Dynamic Choice seem to work as designed.
![screenshot_032515_064627_am](https://cloud.githubusercontent.com/assets/3408226/6823018/aa61c10a-d2ba-11e4-88fe-029bd7bc6af3.jpg)

![screenshot_032515_063940_am](https://cloud.githubusercontent.com/assets/3408226/6822917/bae4b5d8-d2b9-11e4-9da2-dd19b6eac82f.jpg)

![screenshot_032515_064049_am](https://cloud.githubusercontent.com/assets/3408226/6822933/e08b8c12-d2b9-11e4-8809-0ec882d6fc22.jpg)
![screenshot_032515_064347_am](https://cloud.githubusercontent.com/assets/3408226/6822983/4b137158-d2ba-11e4-957a-aa923d3e8fb9.jpg)


![screenshot_032515_064150_am](https://cloud.githubusercontent.com/assets/3408226/6822953/052c35d0-d2ba-11e4-9d96-dc17acfbca9a.jpg)

**Comment by varjojukka** [comment]
@imoutsatsos could you point me to the private-b43e1003-kinow version .hpi file? I tried searching the google groups topics with no luck. Seems like I'm using the version appearing in your "downgrade to" button, which could explain all this :)

**Comment by imoutsatsos** [comment]
@kinow Hi Bruno. Can we make the most recent update of Uno-Choice available through the BioUno update center? Even if it just works with the workaround you've suggested https://github.com/biouno/uno-choice-plugin/issues/76

@varjojukka while waiting for an easy way to get to the latest update, perhaps you could build it from source https://github.com/biouno/uno-choice-plugin

@varjojukka I've tested your issue with a test instance of Jenkins we have for troubleshooting issues. It always has the most recent version (bleeding edge) of the plugin. Unfortunately, I don't have an easy way to get to the hpi. Later today I'll test this issue at work where I have the same version as you have and I'll provide some additional feedback.

**Comment by kinow** [comment]
Sure @imoutsatsos, should we release it as 0.x until we get the update center fixed?

**Comment by imoutsatsos** [comment]
@kinow yes that sounds good. How about v. 0.24. Can we put it in the releases repository where update center gets its updates so that when it gets fixed we can pick up and continue from there. We can then share the link on the dev forum and BioUno?

**Comment by kinow** [comment]
Done http://biouno.org/jenkins-update-center/releases/org/biouno/uno-choice/

@imoutsatsos can you send the announcement to the dev forum? :-) You can pick any previous release announcement as basis

**Comment by varjojukka** [comment]
@imoutsatsos are you triggering the build with Build Triggers > Build periodically ? Still not working for me with the latest version.

**Comment by imoutsatsos** [comment]
@varjojukka Build is triggered manually from the build button. Sorry if I miss-understood...

**Comment by varjojukka** [comment]
@imoutsatsos I could have been more clear about his too, don't worry about it. But yes, the problem specifically exists with non-user triggered builds for example when using the periodical build timer.

**Comment by kinow** [comment]
Created https://issues.jenkins-ci.org/browse/JENKINS-28735 to track this now in Active Choices 1.0. Please feel free to watch & comment on the issue to track its status and help us to fix it. Thanks!
